### ISSUE TITLE
2.0.2 Release still refers "chokidar": "^1.6.1"

### ISSUE THREAD

**Issue by msvinth** [css/csso-cli#15]
In master branch the dependency chokidar has been updated to ^2.0.0 which is great.
However in release 2.0.2 (Tag) it still uses "chokidar": "^1.6.1" which has these security issues: [https://snyk.io/test/npm/chokidar/1.7.0](https://snyk.io/test/npm/chokidar/1.7.0)
Could you please make a new release that uses "chokidar": "^2.0.0".

**Comment by ameer1234567890** [comment]
+1 This needs attention

**Comment by lahmatiy** [comment]
Fixed in [3.0.0](https://github.com/css/csso-cli/releases/tag/v3.0.0)
