### ISSUE TITLE
Removed from npm?

### ISSUE THREAD

**Issue by markasoftware** [css/csso-cli#2]
Csso cli does not appear to be on npm anymore. Installing gives 404 errors and the npm badge on the readme links to a non existant page.

**Comment by lahmatiy** [comment]
Hello, @markasoftware!

No, it's never been published yet. See details in #1

**Comment by lahmatiy** [comment]
CSSO [3.0](https://github.com/css/csso/releases/tag/v3.0.0) is out and `csso-cli` is published on npm
