### ISSUE TITLE
Extremely slow operation

### ISSUE THREAD

**Issue by craigs100** [css/csso-cli#21]
Linux Mint 20.1 running on Dell XPS15 i9 32GRAM

Running JetBrains WebStorm v2020.3.1

Small test site, pure html. Css written in SCSS files using SCSS plugin to create .css files. CSSO plugin set to respond to changes in .css files to minify them. SCSS plugin operates in less than a second, CSSO is typically taking 1min to run.

Have consulted JetBrains support, it doesn't seem to be their issue. Is it possible CSSO is misconfigured or is it only meant to be used as part of a build server rather than during development? In other IDE's and using other transpilers I can typically make an SCSS adjustment, save it and see it pretty much straight away when refreshing the browser. Not so with CSSO so far.

Please advise.

**Comment by lahmatiy** [comment]
CSSO is pretty fast, so taking a minute or more to minify is surprising to me.
Which version do you use? How big is your CSS file?
Could you please to minify it with the web interface (https://css.github.io/csso/csso.html)? If it will have a poor performance then something wrong with CSSO. If not, the issue will be related to how the csso-cli is launched.

**Comment by craigs100** [comment]
Thanks for the quick reply. The CSS file is 12.6KB. The web interface completed in the blink of an eye. Is there anyway to debug it's launch? It's added as a File Watcher in WebStorm. It has the arguments: -i $FileName$ -o $FileNameWithoutExtension$.min.css which I assume are WebStorm codes. If that's the case I'll head back to JetBrains support.

**Comment by lahmatiy** [comment]
For double sure, try to launch csso-cli outside of WebStorm (in terminal). If it will perform fast, definitely the problem is with WebStorm setup. Probably FS watcher is using long pooling and checking FS once per minute.

**Comment by craigs100** [comment]
CSSO worked instantly in terminal on the same file so I'll now go back to JB and have a word.

Many thanks, sorry to trouble you.
