### ISSUE TITLE
Add `--watch` option

### ISSUE THREAD

**Issue by rijkvanzanten** [css/csso-cli#3]
It would be very useful to have a supported `--watch` options which automatically runs the compression when the source file changes.

**Comment by lahmatiy** [comment]
Could you tell about use cases?

**Comment by rijkvanzanten** [comment]
I like to keep track of the end (built) result when developing a site or app. It's quite handy to be able to view the results without having to re-minify manually when changing the input file.

**Comment by amiut** [comment]
+1

**Comment by lahmatiy** [comment]
[v1.1.0](https://github.com/css/csso-cli/releases/tag/v1.1.0) is out with the feature on board.
